//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ZIYARETCITAKIPOTOMASYONModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ZIYARETCITAKIPOTOMASYONEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ZIYARETCITAKIPOTOMASYONEntities object using the connection string found in the 'ZIYARETCITAKIPOTOMASYONEntities' section of the application configuration file.
        /// </summary>
        public ZIYARETCITAKIPOTOMASYONEntities() : base("name=ZIYARETCITAKIPOTOMASYONEntities", "ZIYARETCITAKIPOTOMASYONEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ZIYARETCITAKIPOTOMASYONEntities object.
        /// </summary>
        public ZIYARETCITAKIPOTOMASYONEntities(string connectionString) : base(connectionString, "ZIYARETCITAKIPOTOMASYONEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ZIYARETCITAKIPOTOMASYONEntities object.
        /// </summary>
        public ZIYARETCITAKIPOTOMASYONEntities(EntityConnection connection) : base(connection, "ZIYARETCITAKIPOTOMASYONEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KULLANICIBILGILER> KULLANICIBILGILER
        {
            get
            {
                if ((_KULLANICIBILGILER == null))
                {
                    _KULLANICIBILGILER = base.CreateObjectSet<KULLANICIBILGILER>("KULLANICIBILGILER");
                }
                return _KULLANICIBILGILER;
            }
        }
        private ObjectSet<KULLANICIBILGILER> _KULLANICIBILGILER;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FIRMAADRES> FIRMAADRES
        {
            get
            {
                if ((_FIRMAADRES == null))
                {
                    _FIRMAADRES = base.CreateObjectSet<FIRMAADRES>("FIRMAADRES");
                }
                return _FIRMAADRES;
            }
        }
        private ObjectSet<FIRMAADRES> _FIRMAADRES;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FIRMABILGILER> FIRMABILGILER
        {
            get
            {
                if ((_FIRMABILGILER == null))
                {
                    _FIRMABILGILER = base.CreateObjectSet<FIRMABILGILER>("FIRMABILGILER");
                }
                return _FIRMABILGILER;
            }
        }
        private ObjectSet<FIRMABILGILER> _FIRMABILGILER;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FIRMAKISILER> FIRMAKISILER
        {
            get
            {
                if ((_FIRMAKISILER == null))
                {
                    _FIRMAKISILER = base.CreateObjectSet<FIRMAKISILER>("FIRMAKISILER");
                }
                return _FIRMAKISILER;
            }
        }
        private ObjectSet<FIRMAKISILER> _FIRMAKISILER;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GFIRMABILGILER> GFIRMABILGILER
        {
            get
            {
                if ((_GFIRMABILGILER == null))
                {
                    _GFIRMABILGILER = base.CreateObjectSet<GFIRMABILGILER>("GFIRMABILGILER");
                }
                return _GFIRMABILGILER;
            }
        }
        private ObjectSet<GFIRMABILGILER> _GFIRMABILGILER;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KODURET> KODURET
        {
            get
            {
                if ((_KODURET == null))
                {
                    _KODURET = base.CreateObjectSet<KODURET>("KODURET");
                }
                return _KODURET;
            }
        }
        private ObjectSet<KODURET> _KODURET;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KULLANICIBILGI> KULLANICIBILGI
        {
            get
            {
                if ((_KULLANICIBILGI == null))
                {
                    _KULLANICIBILGI = base.CreateObjectSet<KULLANICIBILGI>("KULLANICIBILGI");
                }
                return _KULLANICIBILGI;
            }
        }
        private ObjectSet<KULLANICIBILGI> _KULLANICIBILGI;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KULLANICIYETKILENDIRME> KULLANICIYETKILENDIRME
        {
            get
            {
                if ((_KULLANICIYETKILENDIRME == null))
                {
                    _KULLANICIYETKILENDIRME = base.CreateObjectSet<KULLANICIYETKILENDIRME>("KULLANICIYETKILENDIRME");
                }
                return _KULLANICIYETKILENDIRME;
            }
        }
        private ObjectSet<KULLANICIYETKILENDIRME> _KULLANICIYETKILENDIRME;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ZIYARETCI> ZIYARETCI
        {
            get
            {
                if ((_ZIYARETCI == null))
                {
                    _ZIYARETCI = base.CreateObjectSet<ZIYARETCI>("ZIYARETCI");
                }
                return _ZIYARETCI;
            }
        }
        private ObjectSet<ZIYARETCI> _ZIYARETCI;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KULLANICIBILGILER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKULLANICIBILGILER(KULLANICIBILGILER kULLANICIBILGILER)
        {
            base.AddObject("KULLANICIBILGILER", kULLANICIBILGILER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FIRMAADRES EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFIRMAADRES(FIRMAADRES fIRMAADRES)
        {
            base.AddObject("FIRMAADRES", fIRMAADRES);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FIRMABILGILER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFIRMABILGILER(FIRMABILGILER fIRMABILGILER)
        {
            base.AddObject("FIRMABILGILER", fIRMABILGILER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FIRMAKISILER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFIRMAKISILER(FIRMAKISILER fIRMAKISILER)
        {
            base.AddObject("FIRMAKISILER", fIRMAKISILER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GFIRMABILGILER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGFIRMABILGILER(GFIRMABILGILER gFIRMABILGILER)
        {
            base.AddObject("GFIRMABILGILER", gFIRMABILGILER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KODURET EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKODURET(KODURET kODURET)
        {
            base.AddObject("KODURET", kODURET);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KULLANICIBILGI EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKULLANICIBILGI(KULLANICIBILGI kULLANICIBILGI)
        {
            base.AddObject("KULLANICIBILGI", kULLANICIBILGI);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KULLANICIYETKILENDIRME EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKULLANICIYETKILENDIRME(KULLANICIYETKILENDIRME kULLANICIYETKILENDIRME)
        {
            base.AddObject("KULLANICIYETKILENDIRME", kULLANICIYETKILENDIRME);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ZIYARETCI EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToZIYARETCI(ZIYARETCI zIYARETCI)
        {
            base.AddObject("ZIYARETCI", zIYARETCI);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZIYARETCITAKIPOTOMASYONModel", Name="FIRMAADRES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FIRMAADRES : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FIRMAADRES object.
        /// </summary>
        /// <param name="fIRMAADRESID">Initial value of the FIRMAADRESID property.</param>
        public static FIRMAADRES CreateFIRMAADRES(global::System.Int32 fIRMAADRESID)
        {
            FIRMAADRES fIRMAADRES = new FIRMAADRES();
            fIRMAADRES.FIRMAADRESID = fIRMAADRESID;
            return fIRMAADRES;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FIRMAADRESID
        {
            get
            {
                return _FIRMAADRESID;
            }
            set
            {
                if (_FIRMAADRESID != value)
                {
                    OnFIRMAADRESIDChanging(value);
                    ReportPropertyChanging("FIRMAADRESID");
                    _FIRMAADRESID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FIRMAADRESID");
                    OnFIRMAADRESIDChanged();
                }
            }
        }
        private global::System.Int32 _FIRMAADRESID;
        partial void OnFIRMAADRESIDChanging(global::System.Int32 value);
        partial void OnFIRMAADRESIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SOKAK
        {
            get
            {
                return _SOKAK;
            }
            set
            {
                OnSOKAKChanging(value);
                ReportPropertyChanging("SOKAK");
                _SOKAK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SOKAK");
                OnSOKAKChanged();
            }
        }
        private global::System.String _SOKAK;
        partial void OnSOKAKChanging(global::System.String value);
        partial void OnSOKAKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MAHALLE
        {
            get
            {
                return _MAHALLE;
            }
            set
            {
                OnMAHALLEChanging(value);
                ReportPropertyChanging("MAHALLE");
                _MAHALLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MAHALLE");
                OnMAHALLEChanged();
            }
        }
        private global::System.String _MAHALLE;
        partial void OnMAHALLEChanging(global::System.String value);
        partial void OnMAHALLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BINA
        {
            get
            {
                return _BINA;
            }
            set
            {
                OnBINAChanging(value);
                ReportPropertyChanging("BINA");
                _BINA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BINA");
                OnBINAChanged();
            }
        }
        private global::System.String _BINA;
        partial void OnBINAChanging(global::System.String value);
        partial void OnBINAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NO
        {
            get
            {
                return _NO;
            }
            set
            {
                OnNOChanging(value);
                ReportPropertyChanging("NO");
                _NO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NO");
                OnNOChanged();
            }
        }
        private Nullable<global::System.Int32> _NO;
        partial void OnNOChanging(Nullable<global::System.Int32> value);
        partial void OnNOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> KAPINO
        {
            get
            {
                return _KAPINO;
            }
            set
            {
                OnKAPINOChanging(value);
                ReportPropertyChanging("KAPINO");
                _KAPINO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KAPINO");
                OnKAPINOChanged();
            }
        }
        private Nullable<global::System.Int32> _KAPINO;
        partial void OnKAPINOChanging(Nullable<global::System.Int32> value);
        partial void OnKAPINOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GFIRMAID
        {
            get
            {
                return _GFIRMAID;
            }
            set
            {
                OnGFIRMAIDChanging(value);
                ReportPropertyChanging("GFIRMAID");
                _GFIRMAID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GFIRMAID");
                OnGFIRMAIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GFIRMAID;
        partial void OnGFIRMAIDChanging(Nullable<global::System.Int32> value);
        partial void OnGFIRMAIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZIYARETCITAKIPOTOMASYONModel", Name="FIRMABILGILER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FIRMABILGILER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FIRMABILGILER object.
        /// </summary>
        /// <param name="fIRMAID">Initial value of the FIRMAID property.</param>
        public static FIRMABILGILER CreateFIRMABILGILER(global::System.Int32 fIRMAID)
        {
            FIRMABILGILER fIRMABILGILER = new FIRMABILGILER();
            fIRMABILGILER.FIRMAID = fIRMAID;
            return fIRMABILGILER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FIRMAID
        {
            get
            {
                return _FIRMAID;
            }
            set
            {
                if (_FIRMAID != value)
                {
                    OnFIRMAIDChanging(value);
                    ReportPropertyChanging("FIRMAID");
                    _FIRMAID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FIRMAID");
                    OnFIRMAIDChanged();
                }
            }
        }
        private global::System.Int32 _FIRMAID;
        partial void OnFIRMAIDChanging(global::System.Int32 value);
        partial void OnFIRMAIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIRMAAD
        {
            get
            {
                return _FIRMAAD;
            }
            set
            {
                OnFIRMAADChanging(value);
                ReportPropertyChanging("FIRMAAD");
                _FIRMAAD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIRMAAD");
                OnFIRMAADChanged();
            }
        }
        private global::System.String _FIRMAAD;
        partial void OnFIRMAADChanging(global::System.String value);
        partial void OnFIRMAADChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIRMATELEFON
        {
            get
            {
                return _FIRMATELEFON;
            }
            set
            {
                OnFIRMATELEFONChanging(value);
                ReportPropertyChanging("FIRMATELEFON");
                _FIRMATELEFON = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIRMATELEFON");
                OnFIRMATELEFONChanged();
            }
        }
        private global::System.String _FIRMATELEFON;
        partial void OnFIRMATELEFONChanging(global::System.String value);
        partial void OnFIRMATELEFONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIRMASAHIBIADSOYAD
        {
            get
            {
                return _FIRMASAHIBIADSOYAD;
            }
            set
            {
                OnFIRMASAHIBIADSOYADChanging(value);
                ReportPropertyChanging("FIRMASAHIBIADSOYAD");
                _FIRMASAHIBIADSOYAD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIRMASAHIBIADSOYAD");
                OnFIRMASAHIBIADSOYADChanged();
            }
        }
        private global::System.String _FIRMASAHIBIADSOYAD;
        partial void OnFIRMASAHIBIADSOYADChanging(global::System.String value);
        partial void OnFIRMASAHIBIADSOYADChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZIYARETCITAKIPOTOMASYONModel", Name="FIRMAKISILER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FIRMAKISILER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FIRMAKISILER object.
        /// </summary>
        /// <param name="fIRMAKISIID">Initial value of the FIRMAKISIID property.</param>
        public static FIRMAKISILER CreateFIRMAKISILER(global::System.Int32 fIRMAKISIID)
        {
            FIRMAKISILER fIRMAKISILER = new FIRMAKISILER();
            fIRMAKISILER.FIRMAKISIID = fIRMAKISIID;
            return fIRMAKISILER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FIRMAKISIID
        {
            get
            {
                return _FIRMAKISIID;
            }
            set
            {
                if (_FIRMAKISIID != value)
                {
                    OnFIRMAKISIIDChanging(value);
                    ReportPropertyChanging("FIRMAKISIID");
                    _FIRMAKISIID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FIRMAKISIID");
                    OnFIRMAKISIIDChanged();
                }
            }
        }
        private global::System.Int32 _FIRMAKISIID;
        partial void OnFIRMAKISIIDChanging(global::System.Int32 value);
        partial void OnFIRMAKISIIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIRMAKISIAD
        {
            get
            {
                return _FIRMAKISIAD;
            }
            set
            {
                OnFIRMAKISIADChanging(value);
                ReportPropertyChanging("FIRMAKISIAD");
                _FIRMAKISIAD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIRMAKISIAD");
                OnFIRMAKISIADChanged();
            }
        }
        private global::System.String _FIRMAKISIAD;
        partial void OnFIRMAKISIADChanging(global::System.String value);
        partial void OnFIRMAKISIADChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIRMAKISISOYAD
        {
            get
            {
                return _FIRMAKISISOYAD;
            }
            set
            {
                OnFIRMAKISISOYADChanging(value);
                ReportPropertyChanging("FIRMAKISISOYAD");
                _FIRMAKISISOYAD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIRMAKISISOYAD");
                OnFIRMAKISISOYADChanged();
            }
        }
        private global::System.String _FIRMAKISISOYAD;
        partial void OnFIRMAKISISOYADChanging(global::System.String value);
        partial void OnFIRMAKISISOYADChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIRMAKISITELEFON
        {
            get
            {
                return _FIRMAKISITELEFON;
            }
            set
            {
                OnFIRMAKISITELEFONChanging(value);
                ReportPropertyChanging("FIRMAKISITELEFON");
                _FIRMAKISITELEFON = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIRMAKISITELEFON");
                OnFIRMAKISITELEFONChanged();
            }
        }
        private global::System.String _FIRMAKISITELEFON;
        partial void OnFIRMAKISITELEFONChanging(global::System.String value);
        partial void OnFIRMAKISITELEFONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FIRMAID
        {
            get
            {
                return _FIRMAID;
            }
            set
            {
                OnFIRMAIDChanging(value);
                ReportPropertyChanging("FIRMAID");
                _FIRMAID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FIRMAID");
                OnFIRMAIDChanged();
            }
        }
        private Nullable<global::System.Int32> _FIRMAID;
        partial void OnFIRMAIDChanging(Nullable<global::System.Int32> value);
        partial void OnFIRMAIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZIYARETCITAKIPOTOMASYONModel", Name="GFIRMABILGILER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GFIRMABILGILER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GFIRMABILGILER object.
        /// </summary>
        /// <param name="gFIRMAID">Initial value of the GFIRMAID property.</param>
        public static GFIRMABILGILER CreateGFIRMABILGILER(global::System.Int32 gFIRMAID)
        {
            GFIRMABILGILER gFIRMABILGILER = new GFIRMABILGILER();
            gFIRMABILGILER.GFIRMAID = gFIRMAID;
            return gFIRMABILGILER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GFIRMAID
        {
            get
            {
                return _GFIRMAID;
            }
            set
            {
                if (_GFIRMAID != value)
                {
                    OnGFIRMAIDChanging(value);
                    ReportPropertyChanging("GFIRMAID");
                    _GFIRMAID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GFIRMAID");
                    OnGFIRMAIDChanged();
                }
            }
        }
        private global::System.Int32 _GFIRMAID;
        partial void OnGFIRMAIDChanging(global::System.Int32 value);
        partial void OnGFIRMAIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GFIRMAAD
        {
            get
            {
                return _GFIRMAAD;
            }
            set
            {
                OnGFIRMAADChanging(value);
                ReportPropertyChanging("GFIRMAAD");
                _GFIRMAAD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GFIRMAAD");
                OnGFIRMAADChanged();
            }
        }
        private global::System.String _GFIRMAAD;
        partial void OnGFIRMAADChanging(global::System.String value);
        partial void OnGFIRMAADChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GFIRMATELEFON
        {
            get
            {
                return _GFIRMATELEFON;
            }
            set
            {
                OnGFIRMATELEFONChanging(value);
                ReportPropertyChanging("GFIRMATELEFON");
                _GFIRMATELEFON = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GFIRMATELEFON");
                OnGFIRMATELEFONChanged();
            }
        }
        private global::System.String _GFIRMATELEFON;
        partial void OnGFIRMATELEFONChanging(global::System.String value);
        partial void OnGFIRMATELEFONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GFIRMASAHIBIADSOYAD
        {
            get
            {
                return _GFIRMASAHIBIADSOYAD;
            }
            set
            {
                OnGFIRMASAHIBIADSOYADChanging(value);
                ReportPropertyChanging("GFIRMASAHIBIADSOYAD");
                _GFIRMASAHIBIADSOYAD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GFIRMASAHIBIADSOYAD");
                OnGFIRMASAHIBIADSOYADChanged();
            }
        }
        private global::System.String _GFIRMASAHIBIADSOYAD;
        partial void OnGFIRMASAHIBIADSOYADChanging(global::System.String value);
        partial void OnGFIRMASAHIBIADSOYADChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZIYARETCITAKIPOTOMASYONModel", Name="KODURET")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KODURET : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KODURET object.
        /// </summary>
        /// <param name="kODID">Initial value of the KODID property.</param>
        public static KODURET CreateKODURET(global::System.Int32 kODID)
        {
            KODURET kODURET = new KODURET();
            kODURET.KODID = kODID;
            return kODURET;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KODID
        {
            get
            {
                return _KODID;
            }
            set
            {
                if (_KODID != value)
                {
                    OnKODIDChanging(value);
                    ReportPropertyChanging("KODID");
                    _KODID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("KODID");
                    OnKODIDChanged();
                }
            }
        }
        private global::System.Int32 _KODID;
        partial void OnKODIDChanging(global::System.Int32 value);
        partial void OnKODIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZIYARETCIISIM
        {
            get
            {
                return _ZIYARETCIISIM;
            }
            set
            {
                OnZIYARETCIISIMChanging(value);
                ReportPropertyChanging("ZIYARETCIISIM");
                _ZIYARETCIISIM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZIYARETCIISIM");
                OnZIYARETCIISIMChanged();
            }
        }
        private global::System.String _ZIYARETCIISIM;
        partial void OnZIYARETCIISIMChanging(global::System.String value);
        partial void OnZIYARETCIISIMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZIYARETCINO
        {
            get
            {
                return _ZIYARETCINO;
            }
            set
            {
                OnZIYARETCINOChanging(value);
                ReportPropertyChanging("ZIYARETCINO");
                _ZIYARETCINO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZIYARETCINO");
                OnZIYARETCINOChanged();
            }
        }
        private global::System.String _ZIYARETCINO;
        partial void OnZIYARETCINOChanging(global::System.String value);
        partial void OnZIYARETCINOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ZIYARETCIONAY
        {
            get
            {
                return _ZIYARETCIONAY;
            }
            set
            {
                OnZIYARETCIONAYChanging(value);
                ReportPropertyChanging("ZIYARETCIONAY");
                _ZIYARETCIONAY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ZIYARETCIONAY");
                OnZIYARETCIONAYChanged();
            }
        }
        private Nullable<global::System.Boolean> _ZIYARETCIONAY;
        partial void OnZIYARETCIONAYChanging(Nullable<global::System.Boolean> value);
        partial void OnZIYARETCIONAYChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZIYARETCITAKIPOTOMASYONModel", Name="KULLANICIBILGI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KULLANICIBILGI : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KULLANICIBILGI object.
        /// </summary>
        /// <param name="kULLANICIBILGI1">Initial value of the KULLANICIBILGI1 property.</param>
        public static KULLANICIBILGI CreateKULLANICIBILGI(global::System.Int32 kULLANICIBILGI1)
        {
            KULLANICIBILGI kULLANICIBILGI = new KULLANICIBILGI();
            kULLANICIBILGI.KULLANICIBILGI1 = kULLANICIBILGI1;
            return kULLANICIBILGI;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KULLANICIBILGI1
        {
            get
            {
                return _KULLANICIBILGI1;
            }
            set
            {
                if (_KULLANICIBILGI1 != value)
                {
                    OnKULLANICIBILGI1Changing(value);
                    ReportPropertyChanging("KULLANICIBILGI1");
                    _KULLANICIBILGI1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("KULLANICIBILGI1");
                    OnKULLANICIBILGI1Changed();
                }
            }
        }
        private global::System.Int32 _KULLANICIBILGI1;
        partial void OnKULLANICIBILGI1Changing(global::System.Int32 value);
        partial void OnKULLANICIBILGI1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> KULLANICIID
        {
            get
            {
                return _KULLANICIID;
            }
            set
            {
                OnKULLANICIIDChanging(value);
                ReportPropertyChanging("KULLANICIID");
                _KULLANICIID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KULLANICIID");
                OnKULLANICIIDChanged();
            }
        }
        private Nullable<global::System.Int32> _KULLANICIID;
        partial void OnKULLANICIIDChanging(Nullable<global::System.Int32> value);
        partial void OnKULLANICIIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KULLANICIIPNO
        {
            get
            {
                return _KULLANICIIPNO;
            }
            set
            {
                OnKULLANICIIPNOChanging(value);
                ReportPropertyChanging("KULLANICIIPNO");
                _KULLANICIIPNO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KULLANICIIPNO");
                OnKULLANICIIPNOChanged();
            }
        }
        private global::System.String _KULLANICIIPNO;
        partial void OnKULLANICIIPNOChanging(global::System.String value);
        partial void OnKULLANICIIPNOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KULLANICIMACNO
        {
            get
            {
                return _KULLANICIMACNO;
            }
            set
            {
                OnKULLANICIMACNOChanging(value);
                ReportPropertyChanging("KULLANICIMACNO");
                _KULLANICIMACNO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KULLANICIMACNO");
                OnKULLANICIMACNOChanged();
            }
        }
        private global::System.String _KULLANICIMACNO;
        partial void OnKULLANICIMACNOChanging(global::System.String value);
        partial void OnKULLANICIMACNOChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZIYARETCITAKIPOTOMASYONModel", Name="KULLANICIBILGILER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KULLANICIBILGILER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KULLANICIBILGILER object.
        /// </summary>
        /// <param name="kULLANICIID">Initial value of the KULLANICIID property.</param>
        public static KULLANICIBILGILER CreateKULLANICIBILGILER(global::System.Int32 kULLANICIID)
        {
            KULLANICIBILGILER kULLANICIBILGILER = new KULLANICIBILGILER();
            kULLANICIBILGILER.KULLANICIID = kULLANICIID;
            return kULLANICIBILGILER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KULLANICIID
        {
            get
            {
                return _KULLANICIID;
            }
            set
            {
                if (_KULLANICIID != value)
                {
                    OnKULLANICIIDChanging(value);
                    ReportPropertyChanging("KULLANICIID");
                    _KULLANICIID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("KULLANICIID");
                    OnKULLANICIIDChanged();
                }
            }
        }
        private global::System.Int32 _KULLANICIID;
        partial void OnKULLANICIIDChanging(global::System.Int32 value);
        partial void OnKULLANICIIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KULLANICIAD
        {
            get
            {
                return _KULLANICIAD;
            }
            set
            {
                OnKULLANICIADChanging(value);
                ReportPropertyChanging("KULLANICIAD");
                _KULLANICIAD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KULLANICIAD");
                OnKULLANICIADChanged();
            }
        }
        private global::System.String _KULLANICIAD;
        partial void OnKULLANICIADChanging(global::System.String value);
        partial void OnKULLANICIADChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KULLANICISOYAD
        {
            get
            {
                return _KULLANICISOYAD;
            }
            set
            {
                OnKULLANICISOYADChanging(value);
                ReportPropertyChanging("KULLANICISOYAD");
                _KULLANICISOYAD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KULLANICISOYAD");
                OnKULLANICISOYADChanged();
            }
        }
        private global::System.String _KULLANICISOYAD;
        partial void OnKULLANICISOYADChanging(global::System.String value);
        partial void OnKULLANICISOYADChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KULLANICIEMAIL
        {
            get
            {
                return _KULLANICIEMAIL;
            }
            set
            {
                OnKULLANICIEMAILChanging(value);
                ReportPropertyChanging("KULLANICIEMAIL");
                _KULLANICIEMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KULLANICIEMAIL");
                OnKULLANICIEMAILChanged();
            }
        }
        private global::System.String _KULLANICIEMAIL;
        partial void OnKULLANICIEMAILChanging(global::System.String value);
        partial void OnKULLANICIEMAILChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KULLANICISIFRE
        {
            get
            {
                return _KULLANICISIFRE;
            }
            set
            {
                OnKULLANICISIFREChanging(value);
                ReportPropertyChanging("KULLANICISIFRE");
                _KULLANICISIFRE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KULLANICISIFRE");
                OnKULLANICISIFREChanged();
            }
        }
        private global::System.String _KULLANICISIFRE;
        partial void OnKULLANICISIFREChanging(global::System.String value);
        partial void OnKULLANICISIFREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> KULLANICIONAY
        {
            get
            {
                return _KULLANICIONAY;
            }
            set
            {
                OnKULLANICIONAYChanging(value);
                ReportPropertyChanging("KULLANICIONAY");
                _KULLANICIONAY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KULLANICIONAY");
                OnKULLANICIONAYChanged();
            }
        }
        private Nullable<global::System.Boolean> _KULLANICIONAY;
        partial void OnKULLANICIONAYChanging(Nullable<global::System.Boolean> value);
        partial void OnKULLANICIONAYChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZIYARETCITAKIPOTOMASYONModel", Name="KULLANICIYETKILENDIRME")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KULLANICIYETKILENDIRME : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KULLANICIYETKILENDIRME object.
        /// </summary>
        /// <param name="yETKIID">Initial value of the YETKIID property.</param>
        public static KULLANICIYETKILENDIRME CreateKULLANICIYETKILENDIRME(global::System.Int32 yETKIID)
        {
            KULLANICIYETKILENDIRME kULLANICIYETKILENDIRME = new KULLANICIYETKILENDIRME();
            kULLANICIYETKILENDIRME.YETKIID = yETKIID;
            return kULLANICIYETKILENDIRME;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 YETKIID
        {
            get
            {
                return _YETKIID;
            }
            set
            {
                if (_YETKIID != value)
                {
                    OnYETKIIDChanging(value);
                    ReportPropertyChanging("YETKIID");
                    _YETKIID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("YETKIID");
                    OnYETKIIDChanged();
                }
            }
        }
        private global::System.Int32 _YETKIID;
        partial void OnYETKIIDChanging(global::System.Int32 value);
        partial void OnYETKIIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> KULLANICIID
        {
            get
            {
                return _KULLANICIID;
            }
            set
            {
                OnKULLANICIIDChanging(value);
                ReportPropertyChanging("KULLANICIID");
                _KULLANICIID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KULLANICIID");
                OnKULLANICIIDChanged();
            }
        }
        private Nullable<global::System.Int32> _KULLANICIID;
        partial void OnKULLANICIIDChanging(Nullable<global::System.Int32> value);
        partial void OnKULLANICIIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KULLANICIYETKIAD
        {
            get
            {
                return _KULLANICIYETKIAD;
            }
            set
            {
                OnKULLANICIYETKIADChanging(value);
                ReportPropertyChanging("KULLANICIYETKIAD");
                _KULLANICIYETKIAD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KULLANICIYETKIAD");
                OnKULLANICIYETKIADChanged();
            }
        }
        private global::System.String _KULLANICIYETKIAD;
        partial void OnKULLANICIYETKIADChanging(global::System.String value);
        partial void OnKULLANICIYETKIADChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZIYARETCITAKIPOTOMASYONModel", Name="ZIYARETCI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ZIYARETCI : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ZIYARETCI object.
        /// </summary>
        /// <param name="zIYARETCIID">Initial value of the ZIYARETCIID property.</param>
        public static ZIYARETCI CreateZIYARETCI(global::System.Int32 zIYARETCIID)
        {
            ZIYARETCI zIYARETCI = new ZIYARETCI();
            zIYARETCI.ZIYARETCIID = zIYARETCIID;
            return zIYARETCI;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ZIYARETCIID
        {
            get
            {
                return _ZIYARETCIID;
            }
            set
            {
                if (_ZIYARETCIID != value)
                {
                    OnZIYARETCIIDChanging(value);
                    ReportPropertyChanging("ZIYARETCIID");
                    _ZIYARETCIID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ZIYARETCIID");
                    OnZIYARETCIIDChanged();
                }
            }
        }
        private global::System.Int32 _ZIYARETCIID;
        partial void OnZIYARETCIIDChanging(global::System.Int32 value);
        partial void OnZIYARETCIIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZIYARETCINO
        {
            get
            {
                return _ZIYARETCINO;
            }
            set
            {
                OnZIYARETCINOChanging(value);
                ReportPropertyChanging("ZIYARETCINO");
                _ZIYARETCINO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZIYARETCINO");
                OnZIYARETCINOChanged();
            }
        }
        private global::System.String _ZIYARETCINO;
        partial void OnZIYARETCINOChanging(global::System.String value);
        partial void OnZIYARETCINOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZIYARETCIKARTNO
        {
            get
            {
                return _ZIYARETCIKARTNO;
            }
            set
            {
                OnZIYARETCIKARTNOChanging(value);
                ReportPropertyChanging("ZIYARETCIKARTNO");
                _ZIYARETCIKARTNO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZIYARETCIKARTNO");
                OnZIYARETCIKARTNOChanged();
            }
        }
        private global::System.String _ZIYARETCIKARTNO;
        partial void OnZIYARETCIKARTNOChanging(global::System.String value);
        partial void OnZIYARETCIKARTNOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> GIRISTARIH
        {
            get
            {
                return _GIRISTARIH;
            }
            set
            {
                OnGIRISTARIHChanging(value);
                ReportPropertyChanging("GIRISTARIH");
                _GIRISTARIH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GIRISTARIH");
                OnGIRISTARIHChanged();
            }
        }
        private Nullable<global::System.DateTime> _GIRISTARIH;
        partial void OnGIRISTARIHChanging(Nullable<global::System.DateTime> value);
        partial void OnGIRISTARIHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> GIRISSAAT
        {
            get
            {
                return _GIRISSAAT;
            }
            set
            {
                OnGIRISSAATChanging(value);
                ReportPropertyChanging("GIRISSAAT");
                _GIRISSAAT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GIRISSAAT");
                OnGIRISSAATChanged();
            }
        }
        private Nullable<global::System.DateTime> _GIRISSAAT;
        partial void OnGIRISSAATChanging(Nullable<global::System.DateTime> value);
        partial void OnGIRISSAATChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CIKISTARIH
        {
            get
            {
                return _CIKISTARIH;
            }
            set
            {
                OnCIKISTARIHChanging(value);
                ReportPropertyChanging("CIKISTARIH");
                _CIKISTARIH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CIKISTARIH");
                OnCIKISTARIHChanged();
            }
        }
        private Nullable<global::System.DateTime> _CIKISTARIH;
        partial void OnCIKISTARIHChanging(Nullable<global::System.DateTime> value);
        partial void OnCIKISTARIHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CIKISSAAT
        {
            get
            {
                return _CIKISSAAT;
            }
            set
            {
                OnCIKISSAATChanging(value);
                ReportPropertyChanging("CIKISSAAT");
                _CIKISSAAT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CIKISSAAT");
                OnCIKISSAATChanged();
            }
        }
        private Nullable<global::System.DateTime> _CIKISSAAT;
        partial void OnCIKISSAATChanging(Nullable<global::System.DateTime> value);
        partial void OnCIKISSAATChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZIYARETCIADSOYAD
        {
            get
            {
                return _ZIYARETCIADSOYAD;
            }
            set
            {
                OnZIYARETCIADSOYADChanging(value);
                ReportPropertyChanging("ZIYARETCIADSOYAD");
                _ZIYARETCIADSOYAD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZIYARETCIADSOYAD");
                OnZIYARETCIADSOYADChanged();
            }
        }
        private global::System.String _ZIYARETCIADSOYAD;
        partial void OnZIYARETCIADSOYADChanging(global::System.String value);
        partial void OnZIYARETCIADSOYADChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CINSIYET
        {
            get
            {
                return _CINSIYET;
            }
            set
            {
                OnCINSIYETChanging(value);
                ReportPropertyChanging("CINSIYET");
                _CINSIYET = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CINSIYET");
                OnCINSIYETChanged();
            }
        }
        private global::System.String _CINSIYET;
        partial void OnCINSIYETChanging(global::System.String value);
        partial void OnCINSIYETChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZIYARETCITIP
        {
            get
            {
                return _ZIYARETCITIP;
            }
            set
            {
                OnZIYARETCITIPChanging(value);
                ReportPropertyChanging("ZIYARETCITIP");
                _ZIYARETCITIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZIYARETCITIP");
                OnZIYARETCITIPChanged();
            }
        }
        private global::System.String _ZIYARETCITIP;
        partial void OnZIYARETCITIPChanging(global::System.String value);
        partial void OnZIYARETCITIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZIYARETCIFIRMA
        {
            get
            {
                return _ZIYARETCIFIRMA;
            }
            set
            {
                OnZIYARETCIFIRMAChanging(value);
                ReportPropertyChanging("ZIYARETCIFIRMA");
                _ZIYARETCIFIRMA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZIYARETCIFIRMA");
                OnZIYARETCIFIRMAChanged();
            }
        }
        private global::System.String _ZIYARETCIFIRMA;
        partial void OnZIYARETCIFIRMAChanging(global::System.String value);
        partial void OnZIYARETCIFIRMAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KIMLIKNO
        {
            get
            {
                return _KIMLIKNO;
            }
            set
            {
                OnKIMLIKNOChanging(value);
                ReportPropertyChanging("KIMLIKNO");
                _KIMLIKNO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KIMLIKNO");
                OnKIMLIKNOChanged();
            }
        }
        private global::System.String _KIMLIKNO;
        partial void OnKIMLIKNOChanging(global::System.String value);
        partial void OnKIMLIKNOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZIYARETEDILENFIRMA
        {
            get
            {
                return _ZIYARETEDILENFIRMA;
            }
            set
            {
                OnZIYARETEDILENFIRMAChanging(value);
                ReportPropertyChanging("ZIYARETEDILENFIRMA");
                _ZIYARETEDILENFIRMA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZIYARETEDILENFIRMA");
                OnZIYARETEDILENFIRMAChanged();
            }
        }
        private global::System.String _ZIYARETEDILENFIRMA;
        partial void OnZIYARETEDILENFIRMAChanging(global::System.String value);
        partial void OnZIYARETEDILENFIRMAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZIYARETEDILENKISI
        {
            get
            {
                return _ZIYARETEDILENKISI;
            }
            set
            {
                OnZIYARETEDILENKISIChanging(value);
                ReportPropertyChanging("ZIYARETEDILENKISI");
                _ZIYARETEDILENKISI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZIYARETEDILENKISI");
                OnZIYARETEDILENKISIChanged();
            }
        }
        private global::System.String _ZIYARETEDILENKISI;
        partial void OnZIYARETEDILENKISIChanging(global::System.String value);
        partial void OnZIYARETEDILENKISIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] ZIYARETRESIM
        {
            get
            {
                return StructuralObject.GetValidValue(_ZIYARETRESIM);
            }
            set
            {
                OnZIYARETRESIMChanging(value);
                ReportPropertyChanging("ZIYARETRESIM");
                _ZIYARETRESIM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZIYARETRESIM");
                OnZIYARETRESIMChanged();
            }
        }
        private global::System.Byte[] _ZIYARETRESIM;
        partial void OnZIYARETRESIMChanging(global::System.Byte[] value);
        partial void OnZIYARETRESIMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ZIYARETID
        {
            get
            {
                return _ZIYARETID;
            }
            set
            {
                OnZIYARETIDChanging(value);
                ReportPropertyChanging("ZIYARETID");
                _ZIYARETID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ZIYARETID");
                OnZIYARETIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ZIYARETID;
        partial void OnZIYARETIDChanging(Nullable<global::System.Int32> value);
        partial void OnZIYARETIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ZIYARETEDILENID
        {
            get
            {
                return _ZIYARETEDILENID;
            }
            set
            {
                OnZIYARETEDILENIDChanging(value);
                ReportPropertyChanging("ZIYARETEDILENID");
                _ZIYARETEDILENID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ZIYARETEDILENID");
                OnZIYARETEDILENIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ZIYARETEDILENID;
        partial void OnZIYARETEDILENIDChanging(Nullable<global::System.Int32> value);
        partial void OnZIYARETEDILENIDChanged();

        #endregion

    
    }

    #endregion

    
}
